### ISSUE TITLE
Docker compose (improvement)

### ISSUE THREAD

**Issue by filipepmo** [MarioCarrion/todo-api-microservice-example#255]
Hey there,

Super good content here and tutorials!

For the docker startup issue and posgresql or elasticsearch taking too long, there's a trick. I'm using Docker Compose version v2.15.1 at the time of this writting.

Here's an example for posgresql. Inside the docker compose yml file add the depends_on with a condition:

```
depends_on:
      postgres:
        condition: service_healthy
```

Next, in the posgresql service definition add:
```
 healthcheck: # to avoid annoying startup migration error
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```

This way I could even do the database migration programatically (added a cmd/internal/migrate.go). Usually I prefer this way as the migration will occur each time an instance boots (if required).

```
// abridged
if err = m.Up(); err != nil && !errors.Is(err, migrate.ErrNoChange) {
		log.Fatal("Couldn't migrate due to 'migrate up' script failing (3)", zap.Error(err))
		return err
	}

version, dirty, err := m.Version()
log.Info("Database migration completed.", zap.Uint("version", version), zap.Bool("dirty", dirty), zap.Error(err))
```

Thanks for writting the tutorials, they rock. Sharing is caring!

**Comment by MarioCarrion** [comment]
Thanks @filipepmo for the suggestion, I updated the `docker-compose.yml` to use this attribute.

Regarding your other comment about the migration, I typically do it separately because I want to make sure the database migration completes correctly before the new code is introduced that way I can separate the two things, for example when changing a database field it could take longer to complete compared to what the deployment timeout is supposed to be; again it depends on the use case.

Thanks again for opening the issue, take care.
